### ISSUE TITLE
A patch for application with existing "Settings" table

### ISSUE THREAD

**Issue by hungtruongquoc** [hackerESQ/laravel-settings#11]
We already had a data table with the name "settings." Could you have patch to customize the name of the data table?

**Comment by hackeresq** [comment]
This is great idea. Working on a rewrite currently. This probably won't make it to the first iteration, but would be happy to accept PRs for this feature!

**Comment by hackeresq** [comment]
Hey @hungtruongquoc , i've just implemented this on the master branch. Do you want to give it a try? Would be nice to get feedback before adding this to the next release.

Here's the updated readme: https://github.com/hackerESQ/laravel-settings#customize-table-name

Let me know what you think.
