### ISSUE TITLE
error when running "composer install" the first time

### ISSUE THREAD

**Issue by lanphan** [hackerESQ/laravel-settings#12]
Hi,
Thanks for this great package.
I got the error below when using this package with my project using Laravel 5.8:
+ First, I installed this package on my local pc, it's ok (installed, published migration and config files, ran migration).
+ I pushed all changes (composer.json, composer.lock, config/settings.php) to git
+ Next, my staging server pull latest code from git, run "composer install" and got error below:
```
laradock@54bb41192a0d:/var/www/dev$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
...
...
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In Connection.php line 664:
                                                                               
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tenant' in 'where c  
  lause' (SQL: select `value`, `key` from `settings` where `tenant` = )        
                                                                               

In PDOConnection.php line 66:
                                                                               
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tenant' in 'where c  
  lause'                                                                       
                                                                               

In PDOConnection.php line 64:
                                                                               
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tenant' in 'where c  
  lause'                                                                                                                                                
```

And, due to that error, I cannot run migration also (got the same issue above)
--> it's something like egg and chicken dilemma, would you please help to review and show me how to solve this problem?

Ps: I did solve it by manually steps below on staging server:
+ remove your package
+ comment all places using "Settings" facade
+ run "composer install" ok again, run "migration" ok
+ then, install again your package, and revert our source back

However, it's super manual, and I'd like to know better way to solve it.

Thanks.

**Comment by hackeresq** [comment]
Can you confirm this is a fresh install of Laravel with a new database (no migrations)?

**Comment by lanphan** [comment]
@hackerESQ it's not fresh install of Laravel, and not a new database.
This is on-going project, we're in progress to develop it, there are lots of migrations there already.
Noted that, not only my staging server got problem when getting that latest code (including your new package), but also other developers get the same problem too :(

**Comment by hackeresq** [comment]
Sorry for the delay in getting back to you on this. Looks like the second migration (which adds the `tenant` column) did not run. I'd suggest trying:

```
php artisan migrate:refresh
``` 

to see if that helps.

If not, try updating to the new version that was released today, which should solve your issues.
