### ISSUE TITLE
Getting errror when calling in blade template

### ISSUE THREAD

**Issue by centralcybersecurity** [hackerESQ/laravel-settings#15]
**ParseError**
syntax error, unexpected '|', expecting variable (T_VARIABLE)

How do I call the setting in the balde template? This - **{{ Settings::get('logo'); }}** - throws above error.

Thanks

**Comment by hackeresq** [comment]
Can you try taking the semicolon out of that snippet?

**Comment by centralcybersecurity** [comment]
> Can you try taking the semicolon out of that snippet?

Thank you.
