### ISSUE TITLE
ParseError ?

### ISSUE THREAD

**Issue by VConsulting** [hackerESQ/laravel-settings#16]
Hello,
I have the following error:
```
        
$test = Settings::get();
dd($test);
```
ParseError
syntax error, unexpected '|', expecting variable (T_VARIABLE)

/vendor/hackeresq/laravel-settings/src/Settings.php

PHP 7.4

**Comment by VConsulting** [comment]
I corrected line 124 of:

    public function get(string|array $key = NULL, string|array $default = NULL)

To

    public function get($key = NULL, $default = NULL)

This seems to be working, is this a PHP version issue?

**Comment by hackeresq** [comment]
Yes, looks like it. Will update the composer dependencies.
