### ISSUE TITLE
Laravel Config file ?

### ISSUE THREAD

**Issue by VConsulting** [hackerESQ/laravel-settings#17]
Hello,
How to be able to call the parameters in the laravel config files:
/config/app.php for example:
  'env' => env ('APP_ENV', 'production'),
through
  'env' => Settings :: get ('APP_ENV'),

**Comment by hackeresq** [comment]
You won't be able to call the Settings facade from within your config files. The application has not been bootstrapped yet.

**Comment by VConsulting** [comment]
Great but then how to manage the parameters in the config files as for the env ()?
