### ISSUE TITLE
tenant migration fails on MySql

### ISSUE THREAD

**Issue by ryancwalsh** [hackerESQ/laravel-settings#8]
I get this error: 
``` SQLSTATE[22004]: Null value not allowed: 1138 Invalid use of NULL value (SQL: alter table `settings` add primary key `settings_key_tenant_primary`(`key`, `tenant`))```

See https://stackoverflow.com/questions/22971586/mysql-alter-table-causes-error-invalid-use-of-null-value

I think this might fix it; change:

`$table->string('tenant')->nullable()->index(); `
To: 
`$table->string('tenant')->default('main')->index(); //https://laravel.com/docs/6.x/migrations#column-modifiers`

Also, you need to change your down() function.

`Schema::dropIfExists('settings');` should only be called in the down() function of the table creation migration.

The down() function of of UpdateSettingsTable should undo specifically what its up() function did.

Also the `if (!Schema::hasColumn('settings', 'tenant')) {` in up() is unnecessary because nobody should be running this UpdateSettingsTable migration except in cases where they don't have the tenant column yet.

**Comment by ryancwalsh** [comment]
These changes in the attached git diff patch file also seem to be necessary.

[laravel-settings-patch.txt](https://github.com/hackerESQ/laravel-settings/files/3741382/laravel-settings-patch.txt)

See https://stackoverflow.com/questions/3418277/how-to-apply-git-diff-patch-without-git-installed

**Comment by hackeresq** [comment]
Thanks for the write up. I'll take a look at this over the weekend.

**Comment by ryancwalsh** [comment]
I would look at https://github.com/hackerESQ/laravel-settings/pull/9 instead of the patch.

**Comment by hackeresq** [comment]
Closed with #9
